import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
    #"~/.config/alacritty/themes/tokyo-night-storm.toml"
    #"~/.config/alacritty/themes/dracula.toml"
    #"~/.config/alacritty/themes/ayu_dark.toml"
    #"~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[window]
opacity = 0.70

[font]
size = 9.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
  family = "JetBrains Mono Nerd Font"
  style = "Bold"

[font.italic]
  family = "JetBrains Mono Nerd Font"
  style = "Italic"

[font.bold_italic]
  family = "JetBrains Mono Nerd Font"
  style = "Bold Italic"
