import = [
    #"~/.config/alacritty/themes/tokyo-night.toml"
    #"~/.config/alacritty/themes/tokyo-night-storm.toml"
    #"~/.config/alacritty/themes/dracula.toml"
    #"~/.config/alacritty/themes/ayu_dark.toml"
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[window]
opacity = 1

[font]
size = 9.5

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"
